### ISSUE TITLE
Stops working after Polyfill component unmounts

### ISSUE THREAD

**Issue by kowalski** [webview-crypto/react-native-webview-crypto#15]
This happens on Android when app is closed and opened again.
The new React component is created but the global module context holds old reference to worker.

**Comment by sirpy** [comment]
I dont have much time to investigate this, but maybe you can suggest a quick fix.
do you have a suggestion for a fix?
can you point me to the code you think is the source of the issue?

**Comment by kowalski** [comment]
@sirpy I was going to ask a colleage to do a PR @ofadiman

I  think the fix is like
```
class PolyfillCrypto extends React.Component {
  constructor(props) {
    super(props);
    this.props = props;
    this.webViewRef = React.createRef();
  }

  shouldComponentUpdate() {
    return false;
  }

  componentWillUnmount() {
    resolveWorker = undefined;
+    workerPromise = new Promise((resolve) => {
+      resolveWorker = resolve;
+    });
  }
```

So basically reset the promise that holds the reference when component is unmounting so that the next one can set the correct reference.

**Comment by kowalski** [comment]
@sirpy @Ofadiman added the pull request with the changes that fix it for us
