### ISSUE TITLE
crypto.subtle.x() functions stuck when called on Expo Android

### ISSUE THREAD

**Issue by adamblvck** [webview-crypto/react-native-webview-crypto#21]
Hi! Thank you for checking out this issue! To keep it brief:

I'm staring a bare project using `expo init`, then follow [this tutorial](https://github.com/aethiop/jot) to fix `Webview-Crypto` imports. Using the latest version of `react-native-webview-crypto` at `0.0.24`.

**On iOS** (hardware and emulator), when calling `crypto.subtle.x()` functions (eg generateKey()), they execute very quickly and efficiently.

**On Android** (hardware and emulator), the MainWorker seems to get stuck when executing the same code:

`App.js` looks like this:
```javascript
<SafeAreaProvider>
      <PolyfillCrypto debug={(verbose) => console.log(verbose)} />
      <AuthProvider>
            <Navigator/>
      </AuthProvider>
</SafeAreaProvider>
```

Upon calling a `crypt.subtle` function, I can see the message being sent to the WebView, but nothing is printed after that. So when executing the following...

```javascript
const hm = await global.crypto.subtle.generateKey({
            name: "RSA-OAEP",
            modulusLength: 4096,
            publicExponent: new Uint8Array([1, 0, 1]),
            hash: "SHA-256"
      },
      true,
      ["encrypt", "decrypt"]
)
```

I'm seeing the following (via the verbose console-debug-print in PolyfillCrypto), meaning that PolyfillCrypto is mounted.

```bash
[webview-crypto] Sending message: {"method":"subtle.generateKey","args":[{"name":"RSA-OAEP","modulusLength":4096,"publicExponent":{"0":1,"1":0,"2":1},"hash":"SHA-256"},true,["encrypt","decrypt"]],"payloadObject":{"method":"subtle.generateKey","id":"494f-a099-9147-18cb-7986-e1b7-7d03-515a","args":[{"name":"RSA-OAEP","modulusLength":4096,"publicExponent":{"0":1,"1":0,"2":1},"hash":"SHA-256"},true,["encrypt","decrypt"]]}}
```

---

**_On iOS, following above message, I see many more messages, and a generated key. On Android the call gets stuck._**

The only thing that I haven't taken care of is the `blank.html` asset, mentioned in the README. Though when looking at the code in the latest version, the part of the code that requires that is commented out. Anyhow, I tried creating the `blank.html` page, and putting it in different places to no avail (Expo managed workflow has no separate `android/.../src/assets` folder).

Any ideas on how to make the PolyfillCrypto work for Expo Android? I've tested this behaviour on 3 different android phones, and two android emulators. Each time a subtle function is being called, the call gets stuck.

Thank you for your time and help! 🙏

**Comment by sirpy** [comment]
Have you tried it not via expo? there's a link to an example repo.
From my experience the issue you are having is usually caused by the import and component loading order.
try to have the index file to only import the webview crypto and polyfill component, and then import the app.js that would contain the main react component.
make sure all the crypto imports are at the top.

**Comment by sirpy** [comment]
what about getRandomValues what are you using for that?

**Comment by adamblvck** [comment]
In `App.js` two crypto libraries are being imported before anything else. When I mess up the order of these two (eg; add below other imports), `Expo/iOS` ceases to work as well.

``` javascript
import 'react-native-get-random-values';
import PolyfillCrypto from 'react-native-webview-crypto';

import React, { ... } from 'react';
import { ... } from 'react-native';

import others from 'xyz';

export default function App() {
	return (	
		<SafeAreaProvider>
			<PolyfillCrypto />
			<AuthProvider>
				<GunDBTestingNavigator/>
			</AuthProvider>
		</SafeAreaProvider>
	);
}
```

- Didn't try to run Android outside of Managed Expo, can try EAS building though I'm not sure that will solve the issue.
- Using `react-native-get-random-values@1.8.0` for getRandomValues

**Comment by adamblvck** [comment]
I can confirm that calling `crypto.getRandomValues()` works on `Expo/Android` using the above setup.

Tried it too with `import { v4 as uuid } from 'uuid';` and calling `uuid()`, which works nicely as well.
