### ISSUE TITLE
InvalidAccessError: key is not extractable

### ISSUE THREAD

**Issue by jaxoncreed** [webview-crypto/react-native-webview-crypto#25]
When running `generateKey` with `extractable` set to false:

```javascript
await generateKey({"name": "ECDSA", "namedCurve": "P-256"}, false, ["sign", "verify"])
```

the following error is always thrown:

```
stringify error InvalidAccessError: key is not extractable
```

This was encountered by others too: https://github.com/smallbets/userbase/issues/275

The above code should generate a key pair with an unextractable private key.

**Comment by sirpy** [comment]
That's simply impossible. As the library is a bridge between native space and the browser. if a key is not extractable it simply cannot be communicated back to the native space from the browser.
