### ISSUE TITLE
Encrypting Base64 Image data fails with "Maximum call stack size exceed"

### ISSUE THREAD

**Issue by reznik99** [webview-crypto/react-native-webview-crypto#26]
Hi there,

As this closed issue points out https://github.com/webview-crypto/react-native-webview-crypto/issues/22

I am getting an error:
```json
{
  "message": "exception in stringify-ing message: subtle.encrypt 6fd0-0d4a-2fda-9ba2-b4f4-86fc-dfc3-f529", 
  "reason": [RangeError: Maximum call stack size exceeded.]
}
```

The exception is thrown by this piece of code:

```js
const cipherText = await crypto.subtle.encrypt(
    {
        name: "AES-CBC",
        iv: IV,
    },
    sessionKey,
    Buffer.from(message)
)
```

Where `sessionKey` is a CryptoKey and `message` is a JSON object as follows:
```js
const message = JSON.stringify({
    type: "IMG",
    message: '<base64 JPG string 583,608 characters long>'
})
```

I am using the following versions:
```json
  "react": "^18.0.0",
  "react-native": "^0.69.7",
  "buffer": "^6.0.3",
  "react-native-webview": "^11.23.1",
  "react-native-webview-crypto": "^0.0.25",
```

Any advice?

Thanks
Francesco

**Comment by reznik99** [comment]
For future reference. I wasn't able to find the cause of this issue.

I got around it by chunking my data and encrypting it in blocks of 48kb.

It's not ideal, but it works now.

**Comment by sirpy** [comment]
I guess there's some data size limits... no idea...
