### ISSUE TITLE
Signing fails on ios for unknown reason

### ISSUE THREAD

**Issue by gotchoices** [webview-crypto/react-native-webview-crypto#27]
We have created a small sample app in the repo:  https://github.com/svinayiw/webcrypto
to demonstrate this problem.  The app runs without error on android, but when running on ios, it generates the error:

The operation failed for an operation-specific reason

We have used this bit of code on several platforms (web, node.js and react-native).  It only seems to fail under react-native on ios.  Can you help us understand:
- Is this a bug/problem in react-native-webview-crypto or perhaps in our usage of it?
- Is there a way to get a more descriptive error back from the method running in the webview

Sorry, there's some unnecessary junk in utils/crypto.ts building up the message to send to subtle.sign.  I've tried setting message to something simpler, like just the string "This is a test message" and I still get the same error.

To replicate:
npm start
npm run ios
In the emulator, press the "Sign key" button
Observe the error message in the console

Can try on android:
hpm start
npm run android
Press button and no error message (and by the way, signing works correctly for us on android)

**Comment by gotchoices** [comment]
I've posted a simplified version of the test app without as much superfluous content here: 
https://github.com/gotchoices/test-webcrypto

**Comment by sirpy** [comment]
Well the following should help you narrow down the issue
1. Does this happen only with this specific encryption scheme?
2. Try running that scheme directly in a webview/safari not via webcrypto to see if this is iOS specific?
3. have you googled about known issues about this scheme in ios/safari?
4. I believe you can modify the JS code running in the webview and add console logs, I think you can view these logs by watching the regular development logs from iOS

**Comment by gotchoices** [comment]
Thanks for the pointers.  Here are some results:

- When the algorithm was set to RSA-PSS, I got that error "The operation failed for an operation-specific reason".  This failure happens only on ios and not on android.
- If I change the algorithm to ECDSA, that error goes away.  The code appears to work, but if I sign a message using sign() via webview-crypto and then try to verify it on the other end under node.js (webcrypto API), the verify fails (only when signature done on ios devices).
- I repeat the above test running the signature on android, the signed record passes the verification fine.
- Interestingly, if I run the signing code in a Safari browser on the same ios simulator, the signature also verifies remotely just fine.

I'm wondering if there is a possibility the key is not getting passed cleanly to the webview.  Or maybe the signature is getting corrupted somewhere as the result of sign() is getting serialized, passed from the webview back to react-native, and then re-jsonified.  

I'm not really sure why it would be unique to ios, but Safari seems to have no problem signing in a way that is compatible with other verifiers.

**Comment by gotchoices** [comment]
Thanks for your input.  Problem solved now.  I still can't get RSA-PSS to run on IOS.  I imagine that is platform-related.  But I do have ECDSA working on both android and IOS.  

The secondary problem was a subtlety I was struggling with to get my message (what was being signed) to be precisely the same at both the signing and verify stages.
