### ISSUE TITLE
Possible Unhandled Promise Rejection when using crypto.subtle.decrypt on iOS / Android

### ISSUE THREAD

**Issue by pmilaszewski** [webview-crypto/react-native-webview-crypto#28]
I'm trying to decrypt data that I received from BE, I'm using the same generated aesKey for that and when I'm trying to call the decrypt method
`await crypto.subtle.decrypt(
        { name: "AES-GCM", iv: iv, additionalData: authData },
        aesKey, authTag)`
        then I receive an warning:
        `Possible Unhandled Promise Rejection (id: 12):
Object {
  "message": "The operation failed for an operation-specific reason",
  "name": "OperationError",
  "stack": "",
}`
It occurs only on iOS / Android, when I'm using the same methods on web itself then it works perfectly. Is there any limitation due to using crypto in webview on mobile apps?

**Comment by sirpy** [comment]
I think some of the encryption schemes are not supported. I think someone
else raised it in the past in one of the closed issues

**Comment by pmilaszewski** [comment]
> I tried to find something about it but I got nothing 😕  but it's weird that encryption works just fine with "AES-GCM" because I'm able to generate encrypted message 🤔
